name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI_TEST_SECRET: ${{ secrets.CI_TEST_SECRET }}

    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Build Docker image
       run: docker build -t arzaai:test .